target-version = "py312"
line-length = 79

[lint]
select = ["E", "W", "F", "I", "N", "UP", "B"]
ignore = ["E501", "B008"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
docstring-code-format = true

[lint.isort]
combine-as-imports = true
lines-after-imports = 2